# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from starrobot_msgs/Fall.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class Fall(genpy.Message):
  _md5sum = "ec4daf7144d18cc51c5e99829b72588d"
  _type = "starrobot_msgs/Fall"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """bool fall1
bool fall2
bool fall3
bool fall4"""
  __slots__ = ['fall1','fall2','fall3','fall4']
  _slot_types = ['bool','bool','bool','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       fall1,fall2,fall3,fall4

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Fall, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.fall1 is None:
        self.fall1 = False
      if self.fall2 is None:
        self.fall2 = False
      if self.fall3 is None:
        self.fall3 = False
      if self.fall4 is None:
        self.fall4 = False
    else:
      self.fall1 = False
      self.fall2 = False
      self.fall3 = False
      self.fall4 = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_4B().pack(_x.fall1, _x.fall2, _x.fall3, _x.fall4))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 4
      (_x.fall1, _x.fall2, _x.fall3, _x.fall4,) = _get_struct_4B().unpack(str[start:end])
      self.fall1 = bool(self.fall1)
      self.fall2 = bool(self.fall2)
      self.fall3 = bool(self.fall3)
      self.fall4 = bool(self.fall4)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_4B().pack(_x.fall1, _x.fall2, _x.fall3, _x.fall4))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 4
      (_x.fall1, _x.fall2, _x.fall3, _x.fall4,) = _get_struct_4B().unpack(str[start:end])
      self.fall1 = bool(self.fall1)
      self.fall2 = bool(self.fall2)
      self.fall3 = bool(self.fall3)
      self.fall4 = bool(self.fall4)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_4B = None
def _get_struct_4B():
    global _struct_4B
    if _struct_4B is None:
        _struct_4B = struct.Struct("<4B")
    return _struct_4B
