# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from starrobot_msgs/Infrared.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class Infrared(genpy.Message):
  _md5sum = "4686eff1b895a48c46b472d5af75db05"
  _type = "starrobot_msgs/Infrared"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """bool infrared1
bool infrared2
bool infrared3
bool infrared4"""
  __slots__ = ['infrared1','infrared2','infrared3','infrared4']
  _slot_types = ['bool','bool','bool','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       infrared1,infrared2,infrared3,infrared4

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Infrared, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.infrared1 is None:
        self.infrared1 = False
      if self.infrared2 is None:
        self.infrared2 = False
      if self.infrared3 is None:
        self.infrared3 = False
      if self.infrared4 is None:
        self.infrared4 = False
    else:
      self.infrared1 = False
      self.infrared2 = False
      self.infrared3 = False
      self.infrared4 = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_4B().pack(_x.infrared1, _x.infrared2, _x.infrared3, _x.infrared4))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 4
      (_x.infrared1, _x.infrared2, _x.infrared3, _x.infrared4,) = _get_struct_4B().unpack(str[start:end])
      self.infrared1 = bool(self.infrared1)
      self.infrared2 = bool(self.infrared2)
      self.infrared3 = bool(self.infrared3)
      self.infrared4 = bool(self.infrared4)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_4B().pack(_x.infrared1, _x.infrared2, _x.infrared3, _x.infrared4))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 4
      (_x.infrared1, _x.infrared2, _x.infrared3, _x.infrared4,) = _get_struct_4B().unpack(str[start:end])
      self.infrared1 = bool(self.infrared1)
      self.infrared2 = bool(self.infrared2)
      self.infrared3 = bool(self.infrared3)
      self.infrared4 = bool(self.infrared4)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_4B = None
def _get_struct_4B():
    global _struct_4B
    if _struct_4B is None:
        _struct_4B = struct.Struct("<4B")
    return _struct_4B
