// Generated by gencpp from file starrobot_msgs/Battery.msg
// DO NOT EDIT!


#ifndef STARROBOT_MSGS_MESSAGE_BATTERY_H
#define STARROBOT_MSGS_MESSAGE_BATTERY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace starrobot_msgs
{
template <class ContainerAllocator>
struct Battery_
{
  typedef Battery_<ContainerAllocator> Type;

  Battery_()
    : voltage(0.0)
    , electricity(0.0)  {
    }
  Battery_(const ContainerAllocator& _alloc)
    : voltage(0.0)
    , electricity(0.0)  {
  (void)_alloc;
    }



   typedef float _voltage_type;
  _voltage_type voltage;

   typedef float _electricity_type;
  _electricity_type electricity;





  typedef boost::shared_ptr< ::starrobot_msgs::Battery_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::starrobot_msgs::Battery_<ContainerAllocator> const> ConstPtr;

}; // struct Battery_

typedef ::starrobot_msgs::Battery_<std::allocator<void> > Battery;

typedef boost::shared_ptr< ::starrobot_msgs::Battery > BatteryPtr;
typedef boost::shared_ptr< ::starrobot_msgs::Battery const> BatteryConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::starrobot_msgs::Battery_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::starrobot_msgs::Battery_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace starrobot_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'starrobot_msgs': ['/home/star/starrobot_ws/src/starrobot/starrobot_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::starrobot_msgs::Battery_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::starrobot_msgs::Battery_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::starrobot_msgs::Battery_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::starrobot_msgs::Battery_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::starrobot_msgs::Battery_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::starrobot_msgs::Battery_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::starrobot_msgs::Battery_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d34fbd3d575d58d32a3790ef4eab2aca";
  }

  static const char* value(const ::starrobot_msgs::Battery_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd34fbd3d575d58d3ULL;
  static const uint64_t static_value2 = 0x2a3790ef4eab2acaULL;
};

template<class ContainerAllocator>
struct DataType< ::starrobot_msgs::Battery_<ContainerAllocator> >
{
  static const char* value()
  {
    return "starrobot_msgs/Battery";
  }

  static const char* value(const ::starrobot_msgs::Battery_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::starrobot_msgs::Battery_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 voltage\n\
float32 electricity\n\
";
  }

  static const char* value(const ::starrobot_msgs::Battery_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::starrobot_msgs::Battery_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.voltage);
      stream.next(m.electricity);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Battery_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::starrobot_msgs::Battery_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::starrobot_msgs::Battery_<ContainerAllocator>& v)
  {
    s << indent << "voltage: ";
    Printer<float>::stream(s, indent + "  ", v.voltage);
    s << indent << "electricity: ";
    Printer<float>::stream(s, indent + "  ", v.electricity);
  }
};

} // namespace message_operations
} // namespace ros

#endif // STARROBOT_MSGS_MESSAGE_BATTERY_H
