// Generated by gencpp from file starrobot_msgs/Encoder.msg
// DO NOT EDIT!


#ifndef STARROBOT_MSGS_MESSAGE_ENCODER_H
#define STARROBOT_MSGS_MESSAGE_ENCODER_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace starrobot_msgs
{
template <class ContainerAllocator>
struct Encoder_
{
  typedef Encoder_<ContainerAllocator> Type;

  Encoder_()
    : MotorEncoder1(0)
    , MotorEncoder2(0)
    , MotorEncoder3(0)
    , MotorEncoder4(0)  {
    }
  Encoder_(const ContainerAllocator& _alloc)
    : MotorEncoder1(0)
    , MotorEncoder2(0)
    , MotorEncoder3(0)
    , MotorEncoder4(0)  {
  (void)_alloc;
    }



   typedef int64_t _MotorEncoder1_type;
  _MotorEncoder1_type MotorEncoder1;

   typedef int64_t _MotorEncoder2_type;
  _MotorEncoder2_type MotorEncoder2;

   typedef int64_t _MotorEncoder3_type;
  _MotorEncoder3_type MotorEncoder3;

   typedef int64_t _MotorEncoder4_type;
  _MotorEncoder4_type MotorEncoder4;





  typedef boost::shared_ptr< ::starrobot_msgs::Encoder_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::starrobot_msgs::Encoder_<ContainerAllocator> const> ConstPtr;

}; // struct Encoder_

typedef ::starrobot_msgs::Encoder_<std::allocator<void> > Encoder;

typedef boost::shared_ptr< ::starrobot_msgs::Encoder > EncoderPtr;
typedef boost::shared_ptr< ::starrobot_msgs::Encoder const> EncoderConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::starrobot_msgs::Encoder_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::starrobot_msgs::Encoder_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace starrobot_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'starrobot_msgs': ['/home/star/starrobot_ws/src/starrobot/starrobot_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::starrobot_msgs::Encoder_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::starrobot_msgs::Encoder_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::starrobot_msgs::Encoder_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::starrobot_msgs::Encoder_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::starrobot_msgs::Encoder_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::starrobot_msgs::Encoder_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::starrobot_msgs::Encoder_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5fcb479f75c8295a0270fd74c95e7c94";
  }

  static const char* value(const ::starrobot_msgs::Encoder_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5fcb479f75c8295aULL;
  static const uint64_t static_value2 = 0x0270fd74c95e7c94ULL;
};

template<class ContainerAllocator>
struct DataType< ::starrobot_msgs::Encoder_<ContainerAllocator> >
{
  static const char* value()
  {
    return "starrobot_msgs/Encoder";
  }

  static const char* value(const ::starrobot_msgs::Encoder_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::starrobot_msgs::Encoder_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 MotorEncoder1\n\
int64 MotorEncoder2\n\
int64 MotorEncoder3\n\
int64 MotorEncoder4\n\
";
  }

  static const char* value(const ::starrobot_msgs::Encoder_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::starrobot_msgs::Encoder_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.MotorEncoder1);
      stream.next(m.MotorEncoder2);
      stream.next(m.MotorEncoder3);
      stream.next(m.MotorEncoder4);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Encoder_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::starrobot_msgs::Encoder_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::starrobot_msgs::Encoder_<ContainerAllocator>& v)
  {
    s << indent << "MotorEncoder1: ";
    Printer<int64_t>::stream(s, indent + "  ", v.MotorEncoder1);
    s << indent << "MotorEncoder2: ";
    Printer<int64_t>::stream(s, indent + "  ", v.MotorEncoder2);
    s << indent << "MotorEncoder3: ";
    Printer<int64_t>::stream(s, indent + "  ", v.MotorEncoder3);
    s << indent << "MotorEncoder4: ";
    Printer<int64_t>::stream(s, indent + "  ", v.MotorEncoder4);
  }
};

} // namespace message_operations
} // namespace ros

#endif // STARROBOT_MSGS_MESSAGE_ENCODER_H
