// Generated by gencpp from file starrobot_msgs/Infrared.msg
// DO NOT EDIT!


#ifndef STARROBOT_MSGS_MESSAGE_INFRARED_H
#define STARROBOT_MSGS_MESSAGE_INFRARED_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace starrobot_msgs
{
template <class ContainerAllocator>
struct Infrared_
{
  typedef Infrared_<ContainerAllocator> Type;

  Infrared_()
    : infrared1(false)
    , infrared2(false)
    , infrared3(false)
    , infrared4(false)  {
    }
  Infrared_(const ContainerAllocator& _alloc)
    : infrared1(false)
    , infrared2(false)
    , infrared3(false)
    , infrared4(false)  {
  (void)_alloc;
    }



   typedef uint8_t _infrared1_type;
  _infrared1_type infrared1;

   typedef uint8_t _infrared2_type;
  _infrared2_type infrared2;

   typedef uint8_t _infrared3_type;
  _infrared3_type infrared3;

   typedef uint8_t _infrared4_type;
  _infrared4_type infrared4;





  typedef boost::shared_ptr< ::starrobot_msgs::Infrared_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::starrobot_msgs::Infrared_<ContainerAllocator> const> ConstPtr;

}; // struct Infrared_

typedef ::starrobot_msgs::Infrared_<std::allocator<void> > Infrared;

typedef boost::shared_ptr< ::starrobot_msgs::Infrared > InfraredPtr;
typedef boost::shared_ptr< ::starrobot_msgs::Infrared const> InfraredConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::starrobot_msgs::Infrared_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::starrobot_msgs::Infrared_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace starrobot_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'starrobot_msgs': ['/home/star/starrobot_ws/src/starrobot/starrobot_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::starrobot_msgs::Infrared_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::starrobot_msgs::Infrared_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::starrobot_msgs::Infrared_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::starrobot_msgs::Infrared_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::starrobot_msgs::Infrared_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::starrobot_msgs::Infrared_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::starrobot_msgs::Infrared_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4686eff1b895a48c46b472d5af75db05";
  }

  static const char* value(const ::starrobot_msgs::Infrared_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4686eff1b895a48cULL;
  static const uint64_t static_value2 = 0x46b472d5af75db05ULL;
};

template<class ContainerAllocator>
struct DataType< ::starrobot_msgs::Infrared_<ContainerAllocator> >
{
  static const char* value()
  {
    return "starrobot_msgs/Infrared";
  }

  static const char* value(const ::starrobot_msgs::Infrared_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::starrobot_msgs::Infrared_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool infrared1\n\
bool infrared2\n\
bool infrared3\n\
bool infrared4\n\
";
  }

  static const char* value(const ::starrobot_msgs::Infrared_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::starrobot_msgs::Infrared_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.infrared1);
      stream.next(m.infrared2);
      stream.next(m.infrared3);
      stream.next(m.infrared4);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Infrared_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::starrobot_msgs::Infrared_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::starrobot_msgs::Infrared_<ContainerAllocator>& v)
  {
    s << indent << "infrared1: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.infrared1);
    s << indent << "infrared2: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.infrared2);
    s << indent << "infrared3: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.infrared3);
    s << indent << "infrared4: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.infrared4);
  }
};

} // namespace message_operations
} // namespace ros

#endif // STARROBOT_MSGS_MESSAGE_INFRARED_H
