// Generated by gencpp from file starrobot_msgs/PowerKey.msg
// DO NOT EDIT!


#ifndef STARROBOT_MSGS_MESSAGE_POWERKEY_H
#define STARROBOT_MSGS_MESSAGE_POWERKEY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace starrobot_msgs
{
template <class ContainerAllocator>
struct PowerKey_
{
  typedef PowerKey_<ContainerAllocator> Type;

  PowerKey_()
    : powerkey1(false)
    , powerkey2(false)
    , powerkey3(false)
    , powerkey4(false)  {
    }
  PowerKey_(const ContainerAllocator& _alloc)
    : powerkey1(false)
    , powerkey2(false)
    , powerkey3(false)
    , powerkey4(false)  {
  (void)_alloc;
    }



   typedef uint8_t _powerkey1_type;
  _powerkey1_type powerkey1;

   typedef uint8_t _powerkey2_type;
  _powerkey2_type powerkey2;

   typedef uint8_t _powerkey3_type;
  _powerkey3_type powerkey3;

   typedef uint8_t _powerkey4_type;
  _powerkey4_type powerkey4;





  typedef boost::shared_ptr< ::starrobot_msgs::PowerKey_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::starrobot_msgs::PowerKey_<ContainerAllocator> const> ConstPtr;

}; // struct PowerKey_

typedef ::starrobot_msgs::PowerKey_<std::allocator<void> > PowerKey;

typedef boost::shared_ptr< ::starrobot_msgs::PowerKey > PowerKeyPtr;
typedef boost::shared_ptr< ::starrobot_msgs::PowerKey const> PowerKeyConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::starrobot_msgs::PowerKey_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::starrobot_msgs::PowerKey_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace starrobot_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'starrobot_msgs': ['/home/star/starrobot_ws/src/starrobot/starrobot_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::starrobot_msgs::PowerKey_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::starrobot_msgs::PowerKey_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::starrobot_msgs::PowerKey_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::starrobot_msgs::PowerKey_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::starrobot_msgs::PowerKey_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::starrobot_msgs::PowerKey_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::starrobot_msgs::PowerKey_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b797b23d4e603a9d30a243a455a1cc76";
  }

  static const char* value(const ::starrobot_msgs::PowerKey_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb797b23d4e603a9dULL;
  static const uint64_t static_value2 = 0x30a243a455a1cc76ULL;
};

template<class ContainerAllocator>
struct DataType< ::starrobot_msgs::PowerKey_<ContainerAllocator> >
{
  static const char* value()
  {
    return "starrobot_msgs/PowerKey";
  }

  static const char* value(const ::starrobot_msgs::PowerKey_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::starrobot_msgs::PowerKey_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool powerkey1\n\
bool powerkey2\n\
bool powerkey3\n\
bool powerkey4\n\
";
  }

  static const char* value(const ::starrobot_msgs::PowerKey_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::starrobot_msgs::PowerKey_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.powerkey1);
      stream.next(m.powerkey2);
      stream.next(m.powerkey3);
      stream.next(m.powerkey4);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PowerKey_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::starrobot_msgs::PowerKey_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::starrobot_msgs::PowerKey_<ContainerAllocator>& v)
  {
    s << indent << "powerkey1: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.powerkey1);
    s << indent << "powerkey2: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.powerkey2);
    s << indent << "powerkey3: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.powerkey3);
    s << indent << "powerkey4: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.powerkey4);
  }
};

} // namespace message_operations
} // namespace ros

#endif // STARROBOT_MSGS_MESSAGE_POWERKEY_H
